const { useState, useEffect, useRef, createContext, useContext } = React;
 
const Icon = ({ name, size=16, color="currentColor", style={} }) => {
  const icons = {
    dashboard: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>,
    restaurants: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6h3.5"/><path d="M16 13v9"/></svg>,
    menu: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>,
    orders: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"/><rect x="9" y="3" width="6" height="4" rx="1"/><path d="M9 12h6M9 16h4"/></svg>,
    inventory: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5M12 22V12"/></svg>,
    finance: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>,
    staff: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
    analytics: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>,
    settings: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>,
    bell: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>,
    sun: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>,
    moon: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>,
    search: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>,
    chevronDown: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9"/></svg>,
    plus: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>,
    edit: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>,
    trash: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6M14 11v6M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>,
    close: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>,
    user: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>,
    globe: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>,
    trending: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>,
    box: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/></svg>,
    receipt: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1z"/><line x1="8" y1="9" x2="16" y2="9"/><line x1="8" y1="13" x2="16" y2="13"/><line x1="8" y1="17" x2="12" y2="17"/></svg>,
    dollar: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>,
    chart: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>,
    truck: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="1" y="3" width="15" height="13" rx="1"/><path d="M16 8h4l3 3v5h-7V8z"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>,
    warning: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>,
    check: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>,
    arrowRight: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>,
    download: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
    upload: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>,
    star: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>,
    fire: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"/></svg>,
    clock: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>,
    card: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg>,
    bag: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>,
    plate: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>,
    link: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>,
    shield: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
    crown: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M2 20h20M5 20l2-10 5 5 5-8 2 13"/></svg>,
    building: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="1"/><path d="M3 9h18M9 21V9"/></svg>,
    printer: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>,
    qr: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><line x1="14" y1="14" x2="21" y2="14"/><line x1="14" y1="18" x2="18" y2="18"/><line x1="21" y1="18" x2="21" y2="21"/></svg>,
    sms: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>,
    push: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/><line x1="12" y1="2" x2="12" y2="4"/></svg>,
    pos: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>,
    palette: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"/></svg>,
    activity: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>,
    info: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>,
  };
  return <span style={{display:"inline-flex",alignItems:"center",flexShrink:0,...style}}>{icons[name]||icons.info}</span>;
};
 
const FestoLogo = ({ size=36 }) => (
  <div style={{width:size,height:size,borderRadius:size*0.22,background:"linear-gradient(135deg,#7B00FF,#9B30FF)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,boxShadow:"0 0 20px rgba(123,0,255,0.5)"}}>
    <svg width={size*0.75} height={size*0.32} viewBox="0 0 60 18" fill="none">
      <text x="0" y="15" fontFamily="Inter,Arial,sans-serif" fontWeight="800" fontSize="17" fill="white" letterSpacing="2">FESTO</text>
    </svg>
  </div>
);
 
 
const AppContext = createContext(null);
function useApp(){return useContext(AppContext);}
const T={ru:{dashboard:"Дашборд",restaurants:"Рестораны",menu:"Меню",orders:"Заказы",inventory:"Склад",finance:"Финансы",staff:"Персонал",analytics:"Аналитика",settings:"Настройки",search:"Поиск...",revenue:"Выручка сегодня",ordersToday:"Заказы",avgCheck:"Средний чек",margin:"Маржинальность",vsYesterday:"vs вчера",vsLastWeek:"vs прошлой нед.",weekRevenue:"Выручка за неделю",total:"Общая",week:"Нед",month:"Мес",year:"Год",topDishes:"Популярные блюда",recentOrders:"Последние заказы",order:"Заказ",time:"Время",type:"Тип",qty:"Кол-во",amount:"Сумма",payment:"Оплата",status:"Статус",action:"Действие",delivery:"Доставка","dine-in":"Зал",pickup:"Самовывоз",active:"Активен",preparing:"Готовится",ready:"Готов",delivered:"Доставлен","on-leave":"Отпуск",addDish:"Добавить блюдо",newDish:"Новое блюдо",dishName:"Название",category:"Категория",sellPrice:"Цена продажи",costPrice:"Себестоимость",create:"Создать блюдо",cancel:"Отмена",stock:"Остаток",hit:"ХИТ","new":"NEW",allCategories:"Все",ingredients:"Ингредиенты и сырьё",addIngredient:"Добавить",newIngredient:"Новый ингредиент",name:"Наименование",supplier:"Поставщик",costPer:"Себест.",minStock:"Мин.остаток",unit:"Ед.изм",lowStockAlert:"Критически мало запасов",income:"Доходы",expense:"Расходы",profit:"Прибыль",cashBook:"Кассовая книга",date:"Дата",description:"Описание",account:"Счёт",addStaff:"Добавить сотрудника",newEmployee:"Новый сотрудник",fullName:"ФИО",position:"Должность",hourlyRate:"Почасовая ставка",hours:"Часы / мес",salary:"Зарплата",generalSettings:"Основные настройки",restaurantName:"Название ресторана",language:"Язык интерфейса",currency:"Валюта",saveChanges:"Сохранить изменения",brandStyle:"Фирменный стиль",accentColor:"Акцентный цвет",preview:"Предпросмотр",online:"Онлайн",domain:"Домен сайта",applyStyle:"Применить стиль",integrations:"Интеграции",roles:"Роли и доступ (RBAC)",configure:"Настроить",connect:"Подключить",change:"Изменить",newRestaurant:"Новый ресторан",cuisine:"Кухня",subdomain:"Поддомен",ownDomain:"Свой домен",template:"Шаблон",createRestaurant:"Создать ресторан",manage:"Управлять",monthRevenue:"Выручка (июнь)",monthOrders:"Заказов за месяц",topDishesTitle:"Топ блюд",details:"Детали",allOrders:"Все заказы",stockPositions:"Позиций на складе",lowStockCount:"Низкий остаток",suppliers:"Поставщиков",stockValue:"Стоимость запасов",receipt:"Поступление",writeOff:"Списание",darkMode:"Тёмная",lightMode:"Светлая"},
en:{dashboard:"Dashboard",restaurants:"Restaurants",menu:"Menu",orders:"Orders",inventory:"Inventory",finance:"Finance",staff:"Staff",analytics:"Analytics",settings:"Settings",search:"Search...",revenue:"Revenue today",ordersToday:"Orders",avgCheck:"Avg. check",margin:"Margin",vsYesterday:"vs yesterday",vsLastWeek:"vs last week",weekRevenue:"Weekly Revenue",total:"Total",week:"Week",month:"Month",year:"Year",topDishes:"Top dishes",recentOrders:"Recent Orders",order:"Order",time:"Time",type:"Type",qty:"Items",amount:"Amount",payment:"Payment",status:"Status",action:"Action",delivery:"Delivery","dine-in":"Dine-in",pickup:"Pickup",active:"Active",preparing:"Preparing",ready:"Ready",delivered:"Delivered","on-leave":"On leave",addDish:"Add dish",newDish:"New Dish",dishName:"Name",category:"Category",sellPrice:"Sell price",costPrice:"Cost price",create:"Create dish",cancel:"Cancel",stock:"Stock",hit:"HIT","new":"NEW",allCategories:"All",ingredients:"Ingredients",addIngredient:"Add",newIngredient:"New Ingredient",name:"Name",supplier:"Supplier",costPer:"Cost",minStock:"Min stock",unit:"Unit",lowStockAlert:"Low stock critical",income:"Income",expense:"Expenses",profit:"Profit",cashBook:"Cash Book",date:"Date",description:"Description",account:"Account",addStaff:"Add staff",newEmployee:"New Employee",fullName:"Full name",position:"Position",hourlyRate:"Hourly rate",hours:"Hours / mo",salary:"Salary",generalSettings:"General Settings",restaurantName:"Restaurant name",language:"Language",currency:"Currency",saveChanges:"Save changes",brandStyle:"Brand Style",accentColor:"Accent color",preview:"Preview",online:"Online",domain:"Website domain",applyStyle:"Apply style",integrations:"Integrations",roles:"Roles & Access",configure:"Configure",connect:"Connect",change:"Change",newRestaurant:"New Restaurant",cuisine:"Cuisine",subdomain:"Subdomain",ownDomain:"Custom domain",template:"Template",createRestaurant:"Create restaurant",manage:"Manage",monthRevenue:"Revenue (June)",monthOrders:"Orders this month",topDishesTitle:"Top dishes",details:"Details",allOrders:"All orders",stockPositions:"Stock positions",lowStockCount:"Low stock",suppliers:"Suppliers",stockValue:"Stock value",receipt:"Receipt",writeOff:"Write-off",darkMode:"Dark",lightMode:"Light"},
zh:{dashboard:"仪表板",restaurants:"餐厅",menu:"菜单",orders:"订单",inventory:"库存",finance:"财务",staff:"员工",analytics:"分析",settings:"设置",search:"搜索...",revenue:"今日营收",ordersToday:"订单数",avgCheck:"平均客单价",margin:"毛利率",vsYesterday:"vs 昨日",vsLastWeek:"vs 上周",weekRevenue:"周营收",total:"合计",week:"周",month:"月",year:"年",topDishes:"热门菜品",recentOrders:"最近订单",order:"订单",time:"时间",type:"类型",qty:"数量",amount:"金额",payment:"支付",status:"状态",action:"操作",delivery:"外卖","dine-in":"堂食",pickup:"自取",active:"活跃",preparing:"准备中",ready:"已准备",delivered:"已送达","on-leave":"请假",addDish:"添加菜品",newDish:"新菜品",dishName:"名称",category:"分类",sellPrice:"售价",costPrice:"成本价",create:"创建菜品",cancel:"取消",stock:"库存",hit:"热销","new":"新品",allCategories:"全部",ingredients:"食材与原料",addIngredient:"添加",newIngredient:"新食材",name:"名称",supplier:"供应商",costPer:"成本",minStock:"最低库存",unit:"单位",lowStockAlert:"库存不足",income:"收入",expense:"支出",profit:"利润",cashBook:"现金账本",date:"日期",description:"描述",account:"账户",addStaff:"添加员工",newEmployee:"新员工",fullName:"姓名",position:"职位",hourlyRate:"时薪",hours:"本月工时",salary:"工资",generalSettings:"基本设置",restaurantName:"餐厅名称",language:"语言",currency:"货币",saveChanges:"保存更改",brandStyle:"品牌样式",accentColor:"主题色",preview:"预览",online:"在线",domain:"网站域名",applyStyle:"应用样式",integrations:"集成",roles:"角色与权限",configure:"配置",connect:"连接",change:"更改",newRestaurant:"新餐厅",cuisine:"菜系",subdomain:"子域名",ownDomain:"自定义域名",template:"模板",createRestaurant:"创建餐厅",manage:"管理",monthRevenue:"营收（六月）",monthOrders:"本月订单",topDishesTitle:"热门菜品",details:"详情",allOrders:"全部订单",stockPositions:"库存项目",lowStockCount:"低库存",suppliers:"供应商",stockValue:"库存价值",receipt:"入库",writeOff:"核销",darkMode:"深色",lightMode:"浅色"},
ja:{dashboard:"ダッシュボード",restaurants:"レストラン",menu:"メニュー",orders:"注文",inventory:"在庫",finance:"財務",staff:"スタッフ",analytics:"分析",settings:"設定",search:"検索...",revenue:"本日の売上",ordersToday:"注文数",avgCheck:"平均客単価",margin:"利益率",vsYesterday:"vs 昨日",vsLastWeek:"vs 先週",weekRevenue:"週間売上",total:"合計",week:"週",month:"月",year:"年",topDishes:"人気料理",recentOrders:"最近の注文",order:"注文",time:"時間",type:"種類",qty:"数量",amount:"金額",payment:"支払",status:"状態",action:"操作",delivery:"デリバリー","dine-in":"店内",pickup:"テイクアウト",active:"アクティブ",preparing:"準備中",ready:"準備完了",delivered:"配達済","on-leave":"休暇",addDish:"料理追加",newDish:"新しい料理",dishName:"名前",category:"カテゴリ",sellPrice:"販売価格",costPrice:"原価",create:"料理を作成",cancel:"キャンセル",stock:"在庫",hit:"ヒット","new":"新着",allCategories:"すべて",ingredients:"食材・原材料",addIngredient:"追加",newIngredient:"新しい食材",name:"名前",supplier:"サプライヤー",costPer:"原価",minStock:"最低在庫",unit:"単位",lowStockAlert:"在庫不足",income:"収入",expense:"支出",profit:"利益",cashBook:"現金出納帳",date:"日付",description:"説明",account:"口座",addStaff:"スタッフ追加",newEmployee:"新しいスタッフ",fullName:"氏名",position:"役職",hourlyRate:"時給",hours:"今月の時間",salary:"給料",generalSettings:"基本設定",restaurantName:"レストラン名",language:"言語",currency:"通貨",saveChanges:"変更を保存",brandStyle:"ブランドスタイル",accentColor:"アクセントカラー",preview:"プレビュー",online:"オンライン",domain:"ウェブドメイン",applyStyle:"スタイル適用",integrations:"連携",roles:"役割とアクセス",configure:"設定",connect:"接続",change:"変更",newRestaurant:"新しいレストラン",cuisine:"料理の種類",subdomain:"サブドメイン",ownDomain:"カスタムドメイン",template:"テンプレート",createRestaurant:"レストランを作成",manage:"管理",monthRevenue:"売上（6月）",monthOrders:"今月の注文",topDishesTitle:"人気料理",details:"詳細",allOrders:"すべての注文",stockPositions:"在庫品目",lowStockCount:"低在庫",suppliers:"サプライヤー",stockValue:"在庫価値",receipt:"入庫",writeOff:"廃棄",darkMode:"ダーク",lightMode:"ライト"},
es:{dashboard:"Panel",restaurants:"Restaurantes",menu:"Menú",orders:"Pedidos",inventory:"Inventario",finance:"Finanzas",staff:"Personal",analytics:"Análisis",settings:"Ajustes",search:"Buscar...",revenue:"Ingresos hoy",ordersToday:"Pedidos",avgCheck:"Ticket medio",margin:"Margen",vsYesterday:"vs ayer",vsLastWeek:"vs semana pasada",weekRevenue:"Ingresos semanales",total:"Total",week:"Sem",month:"Mes",year:"Año",topDishes:"Platos populares",recentOrders:"Pedidos recientes",order:"Pedido",time:"Hora",type:"Tipo",qty:"Cant.",amount:"Importe",payment:"Pago",status:"Estado",action:"Acción",delivery:"Entrega","dine-in":"Sala",pickup:"Recogida",active:"Activo",preparing:"Preparando",ready:"Listo",delivered:"Entregado","on-leave":"Baja",addDish:"Añadir plato",newDish:"Nuevo plato",dishName:"Nombre",category:"Categoría",sellPrice:"Precio",costPrice:"Coste",create:"Crear plato",cancel:"Cancelar",stock:"Stock",hit:"TOP","new":"NUEVO",allCategories:"Todo",ingredients:"Ingredientes",addIngredient:"Añadir",newIngredient:"Nuevo ingrediente",name:"Nombre",supplier:"Proveedor",costPer:"Coste",minStock:"Mín.stock",unit:"Unidad",lowStockAlert:"Stock crítico",income:"Ingresos",expense:"Gastos",profit:"Beneficio",cashBook:"Libro de caja",date:"Fecha",description:"Descripción",account:"Cuenta",addStaff:"Añadir empleado",newEmployee:"Nuevo empleado",fullName:"Nombre completo",position:"Cargo",hourlyRate:"Tarifa/hora",hours:"Horas/mes",salary:"Salario",generalSettings:"Ajustes generales",restaurantName:"Nombre del restaurante",language:"Idioma",currency:"Moneda",saveChanges:"Guardar",brandStyle:"Estilo de marca",accentColor:"Color de acento",preview:"Vista previa",online:"En línea",domain:"Dominio web",applyStyle:"Aplicar",integrations:"Integraciones",roles:"Roles y acceso",configure:"Configurar",connect:"Conectar",change:"Cambiar",newRestaurant:"Nuevo restaurante",cuisine:"Cocina",subdomain:"Subdominio",ownDomain:"Dominio propio",template:"Plantilla",createRestaurant:"Crear restaurante",manage:"Gestionar",monthRevenue:"Ingresos (junio)",monthOrders:"Pedidos del mes",topDishesTitle:"Top platos",details:"Detalles",allOrders:"Todos los pedidos",stockPositions:"Posiciones",lowStockCount:"Stock bajo",suppliers:"Proveedores",stockValue:"Valor del stock",receipt:"Entrada",writeOff:"Baja",darkMode:"Oscuro",lightMode:"Claro"},
fr:{dashboard:"Tableau de bord",restaurants:"Restaurants",menu:"Menu",orders:"Commandes",inventory:"Inventaire",finance:"Finances",staff:"Personnel",analytics:"Analytique",settings:"Paramètres",search:"Rechercher...",revenue:"Recettes aujourd'hui",ordersToday:"Commandes",avgCheck:"Ticket moyen",margin:"Marge",vsYesterday:"vs hier",vsLastWeek:"vs sem. dernière",weekRevenue:"Recettes hebdo",total:"Total",week:"Sem",month:"Mois",year:"An",topDishes:"Plats populaires",recentOrders:"Commandes récentes",order:"Commande",time:"Heure",type:"Type",qty:"Qté",amount:"Montant",payment:"Paiement",status:"Statut",action:"Action",delivery:"Livraison","dine-in":"Salle",pickup:"Emporter",active:"Actif",preparing:"En cours",ready:"Prêt",delivered:"Livré","on-leave":"Congé",addDish:"Ajouter plat",newDish:"Nouveau plat",dishName:"Nom",category:"Catégorie",sellPrice:"Prix",costPrice:"Coût",create:"Créer",cancel:"Annuler",stock:"Stock",hit:"TOP","new":"NOUVEAU",allCategories:"Tout",ingredients:"Ingrédients",addIngredient:"Ajouter",newIngredient:"Nouvel ingrédient",name:"Nom",supplier:"Fournisseur",costPer:"Coût",minStock:"Stock min",unit:"Unité",lowStockAlert:"Stock critique",income:"Recettes",expense:"Dépenses",profit:"Bénéfice",cashBook:"Livre de caisse",date:"Date",description:"Description",account:"Compte",addStaff:"Ajouter employé",newEmployee:"Nouvel employé",fullName:"Nom complet",position:"Poste",hourlyRate:"Taux horaire",hours:"Heures/mois",salary:"Salaire",generalSettings:"Paramètres généraux",restaurantName:"Nom du restaurant",language:"Langue",currency:"Devise",saveChanges:"Enregistrer",brandStyle:"Style de marque",accentColor:"Couleur d'accent",preview:"Aperçu",online:"En ligne",domain:"Domaine web",applyStyle:"Appliquer",integrations:"Intégrations",roles:"Rôles et accès",configure:"Configurer",connect:"Connecter",change:"Modifier",newRestaurant:"Nouveau restaurant",cuisine:"Cuisine",subdomain:"Sous-domaine",ownDomain:"Domaine perso",template:"Modèle",createRestaurant:"Créer restaurant",manage:"Gérer",monthRevenue:"Recettes (juin)",monthOrders:"Commandes du mois",topDishesTitle:"Top plats",details:"Détails",allOrders:"Toutes les commandes",stockPositions:"Positions",lowStockCount:"Stock bas",suppliers:"Fournisseurs",stockValue:"Valeur du stock",receipt:"Entrée",writeOff:"Sortie",darkMode:"Sombre",lightMode:"Clair"}};
const CURRENCIES={RUB:{symbol:"₽",name:"Рубль",locale:"ru-RU"},USD:{symbol:"$",name:"US Dollar",locale:"en-US"},EUR:{symbol:"€",name:"Euro",locale:"de-DE"},IDR:{symbol:"Rp",name:"Rupiah",locale:"id-ID"},JPY:{symbol:"¥",name:"Yen",locale:"ja-JP"},CNY:{symbol:"¥",name:"Yuan",locale:"zh-CN"}};
const RATES={RUB:1,USD:0.011,EUR:0.010,IDR:175,JPY:1.65,CNY:0.079};
function makePalette(dark,accent){
  const a=accent||"#7B00FF";
  const rgb={"#7B00FF":"123,0,255","#FF2D20":"255,45,32","#4B7BFF":"75,123,255","#00E096":"0,224,150","#FFD60A":"255,214,10","#FF6B35":"255,107,53"};
  const aRGB=rgb[a]||"123,0,255";
  if(dark)return{bg:"#080810",surface:"#0F0F1A",card:"#13131F",cardHover:"#1A1A2E",border:"#1E1E30",borderLight:"#2A2A40",red:a,redDim:a+"CC",redGlow:`rgba(${aRGB},0.15)`,redRGB:aRGB,orange:"#FF6B35",text:"#E8E8F4",textMuted:"#7070A0",textDim:"#4A4A6A",green:"#00E096",blue:"#4B7BFF",purple:"#8B5CF6",yellow:"#FFD60A",inputBg:"#0F0F1A"};
  return{bg:"#F4F4F8",surface:"#FFFFFF",card:"#FFFFFF",cardHover:"#F8F8FC",border:"#E0E0EC",borderLight:"#C8C8DC",red:a,redDim:a+"CC",redGlow:`rgba(${aRGB},0.12)`,redRGB:aRGB,orange:"#FF6B35",text:"#111118",textMuted:"#6060A0",textDim:"#A0A0C0",green:"#00B87A",blue:"#3A6AEF",purple:"#7C4CE0",yellow:"#E0B800",inputBg:"#F4F4F8"};
}
const restaurants=[{id:1,name:"Sakura Garden",cuisine:"Japanese",orders:1248,revenue:342800,status:"active"},{id:2,name:"La Bella Italia",cuisine:"Italian",orders:987,revenue:278400,status:"active"},{id:3,name:"Spice Route",cuisine:"Indian",orders:756,revenue:198600,status:"active"}];
const menuItems=[{id:1,name:"Tom Yum Soup",category:"Soups",price:890,cost:234,stock:45,hit:true,isNew:false},{id:2,name:"Pad Thai Classic",category:"Main",price:1200,cost:380,stock:32,hit:false,isNew:true},{id:3,name:"Green Curry",category:"Main",price:1100,cost:310,stock:28,hit:true,isNew:false},{id:4,name:"Mango Sticky Rice",category:"Desserts",price:650,cost:145,stock:60,hit:false,isNew:true},{id:5,name:"Pho Bo",category:"Soups",price:980,cost:267,stock:22,hit:true,isNew:false},{id:6,name:"Spring Rolls",category:"Starters",price:590,cost:120,stock:80,hit:false,isNew:false}];
const menuIcons=["menu","plate","menu","star","menu","bag"];
const revenueData=[{day:"Пн",value:45200},{day:"Вт",value:52800},{day:"Ср",value:48100},{day:"Чт",value:61400},{day:"Пт",value:78900},{day:"Сб",value:94200},{day:"Вс",value:87600}];
const ingredients=[{id:1,name:"Креветки тигровые",category:"Морепродукты",cost:1800,stock:12.4,minStock:5,unit:"кг",supplier:"OceanFresh"},{id:2,name:"Кокосовое молоко",category:"Молочные",cost:320,stock:48,minStock:20,unit:"л",supplier:"TropicGoods"},{id:3,name:"Рис жасминовый",category:"Крупы",cost:180,stock:85,minStock:30,unit:"кг",supplier:"GrainMaster"},{id:4,name:"Лемонграсс",category:"Специи",cost:450,stock:3.2,minStock:5,unit:"кг",supplier:"SpiceWorld"},{id:5,name:"Говядина вырезка",category:"Мясо",cost:2200,stock:18,minStock:10,unit:"кг",supplier:"FarmPrime"},{id:6,name:"Тофу шёлковый",category:"Соя",cost:380,stock:25,minStock:15,unit:"кг",supplier:"TofuCraft"}];
const staffData=[{id:1,name:"Алексей Романов",role:"Шеф-повар",hourlyRate:850,hoursThisMonth:168,status:"active"},{id:2,name:"Мария Соколова",role:"Менеджер зала",hourlyRate:620,hoursThisMonth:152,status:"active"},{id:3,name:"Дмитрий Петров",role:"Бариста",hourlyRate:480,hoursThisMonth:144,status:"active"},{id:4,name:"Анна Козлова",role:"Официант",hourlyRate:420,hoursThisMonth:160,status:"on-leave"}];
const staffIcons=["restaurants","staff","finance","plate"];
const orders=[{id:"#4521",time:"14:32",type:"delivery",items:4,total:3840,status:"preparing",payment:"card"},{id:"#4520",time:"14:28",type:"dine-in",items:6,total:5290,status:"ready",payment:"cash"},{id:"#4519",time:"14:21",type:"pickup",items:2,total:1780,status:"delivered",payment:"qr"},{id:"#4518",time:"14:15",type:"delivery",items:3,total:2650,status:"delivered",payment:"online"},{id:"#4517",time:"14:08",type:"dine-in",items:8,total:7120,status:"delivered",payment:"card"}];
const finances=[{id:1,type:"income",desc:"Выручка от продаж",amount:94200,date:"2026-06-23",category:"Продажи",account:"Касса"},{id:2,type:"expense",desc:"Закупка продуктов",amount:-28400,date:"2026-06-23",category:"Продукты",account:"Р/С"},{id:3,type:"income",desc:"Онлайн-заказы",amount:31600,date:"2026-06-22",category:"Онлайн",account:"Эквайринг"},{id:4,type:"expense",desc:"Зарплата персонала",amount:-52800,date:"2026-06-22",category:"Персонал",account:"Р/С"},{id:5,type:"expense",desc:"Аренда помещения",amount:-85000,date:"2026-06-21",category:"Аренда",account:"Р/С"}];
const NOTIFICATIONS=[{id:1,type:"warning",icon:"warning",title:"Низкий остаток",msg:"Лемонграсс: 3.2 кг (мин. 5 кг)",time:"2 мин назад",read:false},{id:2,type:"success",icon:"check",title:"Заказ #4521 принят",msg:"Доставка · 4 позиции · ₽3 840",time:"5 мин назад",read:false},{id:3,type:"info",icon:"dollar",title:"Выручка за день",msg:"₽94 200 — рост +12% vs вчера",time:"1 ч назад",read:false},{id:4,type:"success",icon:"check",title:"Новый сотрудник добавлен",msg:"Алексей Романов · Шеф-повар",time:"3 ч назад",read:true},{id:5,type:"info",icon:"activity",title:"Отчёт сформирован",msg:"Еженедельный отчёт готов",time:"5 ч назад",read:true},{id:6,type:"warning",icon:"warning",title:"Истекает подписка",msg:"Enterprise · осталось 7 дней",time:"1 д назад",read:true}];
const navItems=[{id:"dashboard",icon:"dashboard"},{id:"restaurants",icon:"restaurants"},{id:"menu",icon:"menu"},{id:"orders",icon:"orders"},{id:"inventory",icon:"inventory"},{id:"finance",icon:"finance"},{id:"staff",icon:"staff"},{id:"analytics",icon:"analytics"},{id:"settings",icon:"settings"}];
function useMobile(){
  const ctx = useContext(AppContext);
  const [m,setM]=useState(window.innerWidth<768);
  useEffect(()=>{const h=()=>setM(window.innerWidth<768);window.addEventListener("resize",h);return()=>window.removeEventListener("resize",h);},[]);
  if(ctx && ctx.viewMode==="mobile") return true;
  if(ctx && ctx.viewMode==="desktop") return false;
  return m;
}
 
 
function MiniChart({data,color,height=40}){const {C}=useApp();const c=color||C.red;const max=Math.max(...data),min=Math.min(...data),range=max-min||1;const w=120,h=height;const pts=data.map((v,i)=>`${(i/(data.length-1))*w},${h-((v-min)/range)*(h-6)-3}`).join(" ");const area=`${pts} ${w},${h} 0,${h}`;const uid="g"+c.replace(/[#,()]/g,"");return(<svg width={w} height={h} style={{overflow:"visible"}}><defs><linearGradient id={uid} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={c} stopOpacity="0.3"/><stop offset="100%" stopColor={c} stopOpacity="0"/></linearGradient></defs><polygon points={area} fill={`url(#${uid})`}/><polyline points={pts} fill="none" stroke={c} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>);}
function BarChart({data}){const {C}=useApp();const max=Math.max(...data.map(d=>d.value));return(<div style={{display:"flex",alignItems:"flex-end",gap:6,height:100,padding:"0 2px"}}>{data.map((d,i)=>{const pct=(d.value/max)*100,isLast=i===data.length-1;return(<div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:3}}><div style={{width:"100%",height:84,display:"flex",alignItems:"flex-end"}}><div style={{width:"100%",height:`${pct}%`,background:isLast?`linear-gradient(180deg,${C.red},${C.redDim})`:`linear-gradient(180deg,${C.border}90,${C.border}40)`,borderRadius:"4px 4px 0 0",transition:"height 0.6s ease",boxShadow:isLast?`0 0 10px rgba(${C.redRGB},0.3)`:"none"}}/></div><span style={{fontSize:9,color:C.textDim}}>{d.day}</span></div>);})}</div>);}
function StatCard({title,value,sub,trend,colorKey="red",iconName,chartData}){const {C}=useApp();const mobile=useMobile();const color=C[colorKey]||C.red;return(<div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"14px 16px":"18px 20px",transition:"all 0.2s",position:"relative",overflow:"hidden"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><div><div style={{fontSize:10,color:C.textMuted,marginBottom:4,letterSpacing:"0.05em",textTransform:"uppercase"}}>{title}</div><div style={{fontSize:mobile?20:26,fontWeight:700,color:C.text,letterSpacing:"-0.02em"}}>{value}</div></div><div style={{background:`rgba(${C.redRGB},0.1)`,borderRadius:10,padding:"8px",flexShrink:0}}><Icon name={iconName} size={18} color={color}/></div></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",flexWrap:"wrap",gap:4}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{color:trend>0?C.green:"#FF6B6B",fontSize:12,fontWeight:600}}>{trend>0?"↑":"↓"} {Math.abs(trend)}%</span><span style={{color:C.textDim,fontSize:11}}>{sub}</span></div>{chartData&&!mobile&&<MiniChart data={chartData} color={color}/>}</div></div>);}
function Badge({status}){const {C,t}=useApp();const map={active:{color:C.green,bg:"rgba(0,224,150,0.1)",label:t("active")},preparing:{color:C.yellow,bg:"rgba(255,214,10,0.1)",label:t("preparing")},ready:{color:C.blue,bg:"rgba(75,123,255,0.1)",label:t("ready")},delivered:{color:C.green,bg:"rgba(0,224,150,0.1)",label:t("delivered")},"on-leave":{color:C.textMuted,bg:"rgba(112,112,160,0.1)",label:t("on-leave")}};const s=map[status]||{color:C.textMuted,bg:"rgba(112,112,160,0.1)",label:status};return <span style={{background:s.bg,color:s.color,borderRadius:6,padding:"3px 8px",fontSize:11,fontWeight:600,whiteSpace:"nowrap"}}>{s.label}</span>;}
function OrderTypeBadge({type}){const {C,t}=useApp();const map={delivery:{icon:"truck",color:C.blue},"dine-in":{icon:"plate",color:C.purple},pickup:{icon:"bag",color:C.orange}};const s=map[type]||{icon:"box",color:C.textMuted};return <span style={{fontSize:12,color:s.color,display:"flex",alignItems:"center",gap:4,whiteSpace:"nowrap"}}><Icon name={s.icon} size={13} color={s.color}/>{t(type)||type}</span>;}
function Modal({open,onClose,title,children}){const {C}=useApp();if(!open)return null;return(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.75)",zIndex:2000,display:"flex",alignItems:"flex-end",justifyContent:"center",backdropFilter:"blur(4px)"}} onClick={onClose}><div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:"20px 20px 0 0",padding:"24px 20px",width:"100%",maxWidth:640,maxHeight:"90vh",overflow:"auto",boxSizing:"border-box"}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h3 style={{color:C.text,fontSize:17,fontWeight:700,margin:0}}>{title}</h3><button onClick={onClose} style={{background:C.surface,border:`1px solid ${C.border}`,color:C.textMuted,cursor:"pointer",borderRadius:8,padding:"6px 8px",display:"flex",alignItems:"center",fontFamily:"inherit"}}><Icon name="close" size={16} color={C.textMuted}/></button></div>{children}</div></div>);}
function InputField({label,value,onChange,type="text",placeholder}){const {C}=useApp();return(<div style={{marginBottom:14}}><label style={{display:"block",color:C.textMuted,fontSize:11,marginBottom:5,textTransform:"uppercase",letterSpacing:"0.05em"}}>{label}</label><input type={type} value={value} onChange={onChange} placeholder={placeholder} style={{width:"100%",background:C.inputBg,border:`1px solid ${C.border}`,borderRadius:10,padding:"11px 14px",color:C.text,fontSize:14,outline:"none",boxSizing:"border-box",fontFamily:"inherit"}} onFocus={e=>e.target.style.borderColor=C.red} onBlur={e=>e.target.style.borderColor=C.border}/></div>);}
function SelectField({label,value,onChange,options}){const {C}=useApp();return(<div style={{marginBottom:14}}><label style={{display:"block",color:C.textMuted,fontSize:11,marginBottom:5,textTransform:"uppercase",letterSpacing:"0.05em"}}>{label}</label><select value={value} onChange={onChange} style={{width:"100%",background:C.inputBg,border:`1px solid ${C.border}`,borderRadius:10,padding:"11px 14px",color:C.text,fontSize:14,outline:"none",boxSizing:"border-box",fontFamily:"inherit",cursor:"pointer"}}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>);}
function Btn({children,onClick,variant="primary",size="md",disabled=false,fullWidth=false}){const {C}=useApp();const [hov,setHov]=useState(false);const styles={primary:{background:`linear-gradient(135deg,${C.red},${C.redDim})`,color:"#fff",border:"none"},secondary:{background:"transparent",color:C.textMuted,border:`1px solid ${C.border}`},ghost:{background:C.surface,color:C.text,border:`1px solid ${C.border}`}};const sizes={sm:"7px 12px",md:"10px 16px",lg:"12px 22px"};return(<button onClick={onClick} disabled={disabled} onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} style={{...styles[variant],padding:sizes[size],borderRadius:10,fontSize:13,fontWeight:600,cursor:disabled?"not-allowed":"pointer",opacity:disabled?0.5:1,transition:"all 0.15s",transform:hov&&!disabled?"translateY(-1px)":"none",boxShadow:hov&&variant==="primary"?`0 4px 16px rgba(${C.redRGB},0.35)`:"none",display:"inline-flex",alignItems:"center",gap:5,fontFamily:"inherit",width:fullWidth?"100%":"auto",justifyContent:fullWidth?"center":"flex-start",whiteSpace:"nowrap"}}>{children}</button>);}
 
function NotifPanel({open,onClose,notifs,onMarkAll}){
  const {C,dark}=useApp();
  if(!open)return null;
  const tc={warning:C.yellow,success:C.green,info:C.blue};
  const tb={warning:"rgba(255,214,10,0.1)",success:"rgba(0,224,150,0.1)",info:"rgba(75,123,255,0.1)"};
  return(<>
    <div style={{position:"fixed",inset:0,zIndex:1500}} onClick={onClose}/>
    <div style={{position:"fixed",top:58,right:14,width:330,maxWidth:"calc(100vw - 28px)",background:dark?"rgba(13,13,26,0.92)":"rgba(255,255,255,0.92)",backdropFilter:"blur(24px) saturate(180%)",WebkitBackdropFilter:"blur(24px) saturate(180%)",border:`1px solid ${dark?"rgba(255,255,255,0.09)":"rgba(0,0,0,0.09)"}`,borderRadius:18,boxShadow:dark?"0 24px 60px rgba(0,0,0,0.65)":"0 24px 60px rgba(0,0,0,0.15)",zIndex:1501,overflow:"hidden"}}>
      <div style={{padding:"14px 16px 12px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:`1px solid ${dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.07)"}`}}>
        <div style={{display:"flex",alignItems:"center",gap:8}}><Icon name="bell" size={15} color={C.text}/><span style={{color:C.text,fontSize:14,fontWeight:700}}>Уведомления</span><span style={{background:`rgba(${C.redRGB},0.15)`,color:C.red,borderRadius:6,padding:"2px 7px",fontSize:11,fontWeight:700}}>{notifs.filter(n=>!n.read).length}</span></div>
        <button onClick={onMarkAll} style={{background:"none",border:"none",color:C.textMuted,cursor:"pointer",fontSize:12,fontFamily:"inherit",padding:"4px 8px",borderRadius:6}} onMouseEnter={e=>e.target.style.color=C.red} onMouseLeave={e=>e.target.style.color=C.textMuted}>Прочитать все</button>
      </div>
      <div style={{maxHeight:360,overflow:"auto"}}>
        {notifs.map(n=>(
          <div key={n.id} style={{padding:"11px 16px",borderBottom:`1px solid ${dark?"rgba(255,255,255,0.04)":"rgba(0,0,0,0.04)"}`,display:"flex",gap:11,alignItems:"flex-start",background:!n.read?(dark?"rgba(255,255,255,0.025)":"rgba(0,0,0,0.018)"):"transparent"}}>
            <div style={{width:32,height:32,borderRadius:9,background:tb[n.type],display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Icon name={n.icon} size={15} color={tc[n.type]}/></div>
            <div style={{flex:1,minWidth:0}}>
              <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:6,marginBottom:2}}><span style={{color:C.text,fontSize:12,fontWeight:n.read?400:600,lineHeight:1.3}}>{n.title}</span>{!n.read&&<div style={{width:6,height:6,borderRadius:"50%",background:C.red,flexShrink:0,marginTop:3}}/>}</div>
              <div style={{color:C.textMuted,fontSize:11,marginBottom:3,lineHeight:1.4}}>{n.msg}</div>
              <div style={{display:"flex",alignItems:"center",gap:3}}><Icon name="clock" size={10} color={C.textDim}/><span style={{color:C.textDim,fontSize:10}}>{n.time}</span></div>
            </div>
          </div>
        ))}
      </div>
      <div style={{padding:"10px 16px",borderTop:`1px solid ${dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.07)"}`,textAlign:"center"}}><button style={{background:"none",border:"none",color:C.textMuted,cursor:"pointer",fontSize:12,fontFamily:"inherit",display:"inline-flex",alignItems:"center",gap:4}} onMouseEnter={e=>e.currentTarget.style.color=C.red} onMouseLeave={e=>e.currentTarget.style.color=C.textMuted}>Все уведомления <Icon name="arrowRight" size={11} color="inherit"/></button></div>
    </div>
  </>);
}
 
function Sidebar({active,onNav,open,onClose}){
  const {C,t,dark,setDark,lang,setLang,currency,setCurrency}=useApp();const mobile=useMobile();
  const content=(<div style={{display:"flex",flexDirection:"column",height:"100%"}}>
    <div style={{padding:"16px 16px 20px",display:"flex",alignItems:"center",gap:10}}>
      <FestoLogo size={36}/><div style={{flex:1}}><div style={{color:C.text,fontSize:15,fontWeight:700,lineHeight:1.1}}>Festo</div><div style={{color:C.textDim,fontSize:10,letterSpacing:"0.08em"}}>ENTERPRISE</div></div>
      {mobile&&<button onClick={onClose} style={{background:"none",border:"none",color:C.textMuted,cursor:"pointer",padding:4,display:"flex"}}><Icon name="close" size={20} color={C.textMuted}/></button>}
    </div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:10,padding:"10px 12px",margin:"0 12px 16px",cursor:"pointer",display:"flex",alignItems:"center",gap:8}}>
      <div style={{width:28,height:28,borderRadius:7,background:`rgba(${C.redRGB},0.15)`,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name="restaurants" size={14} color={C.red}/></div>
      <div style={{flex:1,overflow:"hidden"}}><div style={{color:C.text,fontSize:13,fontWeight:600,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>Sakura Garden</div><div style={{color:C.textDim,fontSize:11}}>3 {t("restaurants").toLowerCase()}</div></div>
      <Icon name="chevronDown" size={14} color={C.textDim}/>
    </div>
    <div style={{flex:1,padding:"0 8px",overflow:"auto"}}>
      {navItems.map(item=>{const isActive=active===item.id;return(<button key={item.id} onClick={()=>{onNav(item.id);if(mobile)onClose();}} style={{background:isActive?C.redGlow:"transparent",border:isActive?`1px solid rgba(${C.redRGB},0.25)`:"1px solid transparent",borderRadius:10,padding:"10px 12px",display:"flex",alignItems:"center",gap:10,cursor:"pointer",transition:"all 0.15s",color:isActive?C.red:C.textMuted,fontFamily:"inherit",fontSize:13,fontWeight:isActive?600:400,textAlign:"left",width:"100%",marginBottom:2}}><Icon name={item.icon} size={16} color={isActive?C.red:C.textMuted}/>{t(item.id)}{item.id==="orders"&&<span style={{marginLeft:"auto",background:C.red,color:"#fff",borderRadius:6,padding:"1px 6px",fontSize:10,fontWeight:700}}>5</span>}</button>);})}
    </div>
    <div style={{padding:"12px 12px 0",borderTop:`1px solid ${C.border}`,marginTop:"auto"}}>
      <button onClick={()=>setDark(d=>!d)} style={{width:"100%",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:"9px 12px",display:"flex",alignItems:"center",gap:8,cursor:"pointer",marginBottom:8,fontFamily:"inherit"}}><Icon name={dark?"sun":"moon"} size={16} color={C.textMuted}/><span style={{color:C.text,fontSize:13}}>{dark?t("lightMode"):t("darkMode")}</span></button>
      <select value={lang} onChange={e=>setLang(e.target.value)} style={{width:"100%",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:"9px 12px",color:C.text,fontSize:13,marginBottom:8,outline:"none",cursor:"pointer",fontFamily:"inherit"}}>
        {[{v:"ru",l:"🇷🇺 Русский"},{v:"en",l:"🇬🇧 English"},{v:"zh",l:"🇨🇳 中文"},{v:"ja",l:"🇯🇵 日本語"},{v:"es",l:"🇪🇸 Español"},{v:"fr",l:"🇫🇷 Français"}].map(x=><option key={x.v} value={x.v}>{x.l}</option>)}
      </select>
      <select value={currency} onChange={e=>setCurrency(e.target.value)} style={{width:"100%",background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,padding:"9px 12px",color:C.text,fontSize:13,marginBottom:12,outline:"none",cursor:"pointer",fontFamily:"inherit"}}>
        {Object.entries(CURRENCIES).map(([k,v])=><option key={k} value={k}>{v.symbol} {k} — {v.name}</option>)}
      </select>
      <div style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0"}}>
        <div style={{width:32,height:32,borderRadius:8,background:`linear-gradient(135deg,${C.blue},${C.purple})`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Icon name="user" size={16} color="#fff"/></div>
        <div><div style={{color:C.text,fontSize:12,fontWeight:600}}>Super Admin</div><div style={{color:C.textDim,fontSize:11}}>admin@festo.io</div></div>
      </div>
    </div>
  </div>);
  if(mobile)return(<>{open&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.6)",zIndex:900,backdropFilter:"blur(2px)"}} onClick={onClose}/>}<div style={{position:"fixed",left:0,top:0,bottom:0,width:260,background:C.surface,borderRight:`1px solid ${C.border}`,zIndex:1000,transform:open?"translateX(0)":"translateX(-100%)",transition:"transform 0.3s cubic-bezier(0.4,0,0.2,1)",overflow:"auto",display:"flex",flexDirection:"column",boxShadow:open?"4px 0 40px rgba(0,0,0,0.4)":"none"}}>{content}</div></>);
  return(<div style={{width:220,background:C.surface,borderRight:`1px solid ${C.border}`,display:"flex",flexDirection:"column",flexShrink:0,overflow:"auto"}}>{content}</div>);
}
 
function TopBar({section,onBurger,notifCount,onBell}){
  const {C,t,dark,setDark}=useApp();const mobile=useMobile();
  return(<div style={{background:C.surface,borderBottom:`1px solid ${C.border}`,padding:mobile?"12px 16px":"14px 24px",display:"flex",alignItems:"center",gap:12,flexShrink:0}}>
    {mobile&&<button onClick={onBurger} style={{background:"none",border:`1px solid ${C.border}`,borderRadius:8,padding:"7px 9px",cursor:"pointer",display:"flex",flexDirection:"column",gap:4,flexShrink:0}}>
      <div style={{width:18,height:2,background:C.text,borderRadius:2}}/><div style={{width:18,height:2,background:C.text,borderRadius:2}}/><div style={{width:12,height:2,background:C.text,borderRadius:2}}/>
    </button>}
    <h1 style={{color:C.text,fontSize:mobile?17:20,fontWeight:700,margin:0,flex:"none"}}>{t(section)}</h1>
    {!mobile&&<div style={{flex:1,maxWidth:320,position:"relative"}}><span style={{position:"absolute",left:11,top:"50%",transform:"translateY(-50%)",display:"flex"}}><Icon name="search" size={14} color={C.textDim}/></span><input placeholder={t("search")} style={{width:"100%",background:C.card,border:`1px solid ${C.border}`,borderRadius:10,padding:"8px 12px 8px 34px",color:C.text,fontSize:13,outline:"none",boxSizing:"border-box",fontFamily:"inherit"}}/></div>}
    <div style={{marginLeft:"auto",display:"flex",gap:8,alignItems:"center"}}>
      {!mobile&&<button onClick={()=>setDark(d=>!d)} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:10,padding:"8px",cursor:"pointer",display:"flex",alignItems:"center"}}><Icon name={dark?"sun":"moon"} size={16} color={C.textMuted}/></button>}
      <button onClick={onBell} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:10,padding:"8px",cursor:"pointer",display:"flex",alignItems:"center",position:"relative"}}>
        <Icon name="bell" size={16} color={C.textMuted}/>
        {notifCount>0&&<span style={{position:"absolute",top:5,right:5,width:7,height:7,borderRadius:"50%",background:C.red,border:`2px solid ${C.surface}`}}/>}
      </button>
    </div>
  </div>);
}
 
 
function DashboardPage(){const {C,t,fmt}=useApp();const mobile=useMobile();return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr 1fr":"repeat(4,1fr)",gap:12,marginBottom:20}}>
    <StatCard title={t("revenue")} value={fmt(94200)} sub={t("vsYesterday")} trend={12.4} iconName="dollar" chartData={[45,52,48,61,78,94,87]}/>
    <StatCard title={t("ordersToday")} value="81" sub={t("vsYesterday")} trend={8.2} iconName="receipt" colorKey="blue" chartData={[38,44,41,52,67,81,74]}/>
    <StatCard title={t("avgCheck")} value={fmt(1163)} sub={t("vsYesterday")} trend={3.8} iconName="trending" colorKey="purple" chartData={[1090,1150,1100,1180,1130,1163,1140]}/>
    <StatCard title={t("margin")} value="68.4%" sub={t("vsLastWeek")} trend={-2.1} iconName="chart" colorKey="orange" chartData={[70,72,68,71,69,68,68]}/>
  </div>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"2fr 1fr",gap:14,marginBottom:20}}>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"20px"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16,flexWrap:"wrap",gap:8}}>
        <div><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:2}}>{t("weekRevenue")}</div><div style={{color:C.textMuted,fontSize:12}}>{t("total")}: {fmt(468200)}</div></div>
        <div style={{display:"flex",gap:6}}>{[t("week"),t("month"),t("year")].map((tt,i)=><button key={i} style={{background:i===0?C.redGlow:"transparent",border:`1px solid ${i===0?"rgba("+C.redRGB+",0.3)":C.border}`,borderRadius:7,padding:"5px 9px",fontSize:11,color:i===0?C.red:C.textMuted,cursor:"pointer",fontFamily:"inherit"}}>{tt}</button>)}</div>
      </div>
      <BarChart data={revenueData}/>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:6}}>{revenueData.map(d=><div key={d.day} style={{flex:1,textAlign:"center"}}><div style={{color:C.textDim,fontSize:9}}>{fmt(d.value/1000,"k")}</div></div>)}</div>
    </div>
    {!mobile&&<div style={{display:"flex",flexDirection:"column",gap:14}}>
      <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:18}}>
        <div style={{color:C.textMuted,fontSize:11,marginBottom:10,textTransform:"uppercase",letterSpacing:"0.05em"}}>{t("restaurants")}</div>
        {restaurants.map(r=><div key={r.id} style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}>
          <div style={{width:28,height:28,borderRadius:7,background:`rgba(${C.redRGB},0.1)`,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name="restaurants" size={14} color={C.red}/></div>
          <div style={{flex:1}}><div style={{color:C.text,fontSize:13,fontWeight:600}}>{r.name}</div><div style={{color:C.textDim,fontSize:11}}>{r.cuisine}</div></div>
          <div style={{color:C.green,fontSize:12,fontWeight:600}}>{fmt(r.revenue)}</div>
        </div>)}
      </div>
      <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:18}}>
        <div style={{color:C.textMuted,fontSize:11,marginBottom:10,textTransform:"uppercase",letterSpacing:"0.05em"}}>{t("topDishes")}</div>
        {menuItems.filter(m=>m.hit).slice(0,3).map((item,i)=><div key={item.id} style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}>
          <span style={{color:C.textDim,fontSize:11,width:14}}>#{i+1}</span>
          <div style={{width:26,height:26,borderRadius:7,background:C.surface,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name="menu" size={13} color={C.textMuted}/></div>
          <div style={{flex:1,color:C.text,fontSize:13}}>{item.name}</div>
          <span style={{color:C.text,fontSize:13,fontWeight:600}}>{fmt(item.price)}</span>
        </div>)}
      </div>
    </div>}
  </div>
  <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"20px"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}>
      <div style={{color:C.text,fontSize:15,fontWeight:700}}>{t("recentOrders")}</div>
      <Btn variant="ghost" size="sm"><Icon name="arrowRight" size={13} color={C.textMuted}/>{t("allOrders")}</Btn>
    </div>
    {mobile?(<div style={{display:"flex",flexDirection:"column",gap:10}}>{orders.map(o=><div key={o.id} style={{background:C.surface,borderRadius:10,padding:"12px 14px",border:`1px solid ${C.border}`}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{color:C.text,fontWeight:700,fontSize:14}}>{o.id}</span><Badge status={o.status}/></div>
      <div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><OrderTypeBadge type={o.type}/><span style={{color:C.textDim,fontSize:12}}>{o.time}</span><span style={{color:C.text,fontWeight:700,fontSize:13,marginLeft:"auto"}}>{fmt(o.total)}</span></div>
    </div>)}</div>):(<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:560}}><thead><tr style={{borderBottom:`1px solid ${C.border}`}}>{[t("order"),t("time"),t("type"),t("qty"),t("amount"),t("payment"),t("status")].map(h=><th key={h} style={{color:C.textDim,fontSize:10,fontWeight:600,textAlign:"left",padding:"0 8px 10px",textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} style={{borderBottom:`1px solid ${C.border}`}}><td style={{padding:"11px 8px",color:C.text,fontSize:13,fontWeight:600}}>{o.id}</td><td style={{padding:"11px 8px",color:C.textMuted,fontSize:12}}>{o.time}</td><td style={{padding:"11px 8px"}}><OrderTypeBadge type={o.type}/></td><td style={{padding:"11px 8px",color:C.textMuted,fontSize:12}}>{o.items}</td><td style={{padding:"11px 8px",color:C.text,fontSize:13,fontWeight:600}}>{fmt(o.total)}</td><td style={{padding:"11px 8px",color:C.textMuted,fontSize:11}}>{o.payment}</td><td style={{padding:"11px 8px"}}><Badge status={o.status}/></td></tr>)}</tbody></table></div>)}
  </div>
</div>);}
 
function MenuPage(){const {C,t,fmt}=useApp();const mobile=useMobile();const [showModal,setShowModal]=useState(false);const [newItem,setNewItem]=useState({name:"",category:"Main",price:"",cost:""});const [items,setItems]=useState(menuItems);const [activeCat,setActiveCat]=useState("all");const cats=["all","Soups","Main","Starters","Desserts"];const filtered=activeCat==="all"?items:items.filter(i=>i.category===activeCat);const handleAdd=()=>{if(!newItem.name||!newItem.price)return;setItems(p=>[...p,{id:Date.now(),...newItem,price:+newItem.price,cost:+newItem.cost,stock:50,hit:false,isNew:true}]);setShowModal(false);setNewItem({name:"",category:"Main",price:"",cost:""});};
return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16,gap:10,flexWrap:"wrap"}}>
    <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{cats.map(c=><button key={c} onClick={()=>setActiveCat(c)} style={{background:activeCat===c?C.redGlow:C.card,border:`1px solid ${activeCat===c?"rgba("+C.redRGB+",0.3)":C.border}`,borderRadius:8,padding:"7px 12px",fontSize:12,color:activeCat===c?C.red:C.textMuted,cursor:"pointer",fontFamily:"inherit",fontWeight:activeCat===c?600:400}}>{c==="all"?t("allCategories"):c}</button>)}</div>
    <Btn onClick={()=>setShowModal(true)}><Icon name="plus" size={14} color="#fff"/>{t("addDish")}</Btn>
  </div>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr 1fr":"repeat(3,1fr)",gap:12}}>
    {filtered.map((item,idx)=>{const margin=((item.price-item.cost)/item.price*100).toFixed(0);return(<div key={item.id} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"14px":"18px",transition:"all 0.2s"}} onMouseEnter={e=>e.currentTarget.style.borderColor=C.borderLight} onMouseLeave={e=>e.currentTarget.style.borderColor=C.border}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}>
        <div style={{width:42,height:42,borderRadius:11,background:`rgba(${C.redRGB},0.08)`,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name={menuIcons[item.id-1]||"menu"} size={20} color={C.red}/></div>
        <div style={{display:"flex",gap:4,flexWrap:"wrap",justifyContent:"flex-end"}}>
          {item.hit&&<span style={{background:`rgba(${C.redRGB},0.1)`,color:C.red,borderRadius:5,padding:"2px 6px",fontSize:9,fontWeight:700,display:"flex",alignItems:"center",gap:2}}><Icon name="fire" size={9} color={C.red}/>{t("hit")}</span>}
          {item.isNew&&<span style={{background:"rgba(0,224,150,0.1)",color:C.green,borderRadius:5,padding:"2px 6px",fontSize:9,fontWeight:700,display:"flex",alignItems:"center",gap:2}}><Icon name="star" size={9} color={C.green}/>{t("new")}</span>}
        </div>
      </div>
      <div style={{color:C.text,fontSize:mobile?13:14,fontWeight:700,marginBottom:3,lineHeight:1.3}}>{item.name}</div>
      <div style={{color:C.textDim,fontSize:11,marginBottom:10}}>{item.category}</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:10}}>
        {[{label:t("sellPrice").split(" ")[0],val:fmt(item.price)},{label:t("costPrice").split(" ")[0],val:fmt(item.cost)},{label:"Маржа",val:margin+"%",color:+margin>60?C.green:C.yellow}].map(s=><div key={s.label} style={{background:C.surface,borderRadius:7,padding:"7px 8px"}}><div style={{color:C.textDim,fontSize:9}}>{s.label}</div><div style={{color:s.color||C.text,fontSize:12,fontWeight:700}}>{s.val}</div></div>)}
      </div>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}>
        <div style={{display:"flex",alignItems:"center",gap:5}}><div style={{width:7,height:7,borderRadius:"50%",background:item.stock>20?C.green:C.red}}/><span style={{color:C.textMuted,fontSize:11}}>{t("stock")}: {item.stock}</span></div>
        <div style={{display:"flex",gap:4}}><Btn variant="ghost" size="sm"><Icon name="edit" size={13} color={C.textMuted}/></Btn><Btn variant="ghost" size="sm"><Icon name="trash" size={13} color={C.textMuted}/></Btn></div>
      </div>
    </div>);})}
  </div>
  <Modal open={showModal} onClose={()=>setShowModal(false)} title={t("newDish")}>
    <InputField label={t("dishName")} value={newItem.name} onChange={e=>setNewItem(p=>({...p,name:e.target.value}))} placeholder="Tom Yum"/>
    <SelectField label={t("category")} value={newItem.category} onChange={e=>setNewItem(p=>({...p,category:e.target.value}))} options={["Main","Soups","Starters","Desserts"].map(v=>({value:v,label:v}))}/>
    <InputField label={t("sellPrice")} value={newItem.price} onChange={e=>setNewItem(p=>({...p,price:e.target.value}))} type="number" placeholder="1200"/>
    <InputField label={t("costPrice")} value={newItem.cost} onChange={e=>setNewItem(p=>({...p,cost:e.target.value}))} type="number" placeholder="380"/>
    <div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:20}}><Btn variant="secondary" onClick={()=>setShowModal(false)}>{t("cancel")}</Btn><Btn onClick={handleAdd}>{t("create")}</Btn></div>
  </Modal>
</div>);}
 
function InventoryPage(){const {C,t,fmt}=useApp();const mobile=useMobile();const [showModal,setShowModal]=useState(false);const [items,setItems]=useState(ingredients);const [newIng,setNewIng]=useState({name:"",category:"",cost:"",stock:"",minStock:"",unit:"кг",supplier:""});const lowStock=items.filter(i=>i.stock<=i.minStock);const handleAdd=()=>{if(!newIng.name)return;setItems(p=>[...p,{id:Date.now(),...newIng,cost:+newIng.cost,stock:+newIng.stock,minStock:+newIng.minStock}]);setShowModal(false);setNewIng({name:"",category:"",cost:"",stock:"",minStock:"",unit:"кг",supplier:""});};
return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  {lowStock.length>0&&<div style={{background:`rgba(${C.redRGB},0.08)`,border:`1px solid rgba(${C.redRGB},0.2)`,borderRadius:10,padding:"12px 16px",marginBottom:16,display:"flex",alignItems:"flex-start",gap:8}}><Icon name="warning" size={16} color={C.yellow}/><span style={{color:C.red,fontSize:12,fontWeight:600}}>{t("lowStockAlert")}: {lowStock.map(i=>i.name).join(", ")}</span></div>}
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr 1fr":"repeat(4,1fr)",gap:12,marginBottom:20}}>
    {[{label:t("stockPositions"),value:items.length,icon:"box"},{label:t("lowStockCount"),value:lowStock.length,icon:"warning",urgent:true},{label:t("suppliers"),value:[...new Set(items.map(i=>i.supplier))].length,icon:"truck"},{label:t("stockValue"),value:fmt(items.reduce((s,i)=>s+i.cost*i.stock,0).toFixed(0)),icon:"dollar"}].map(s=><div key={s.label} style={{background:C.card,border:`1px solid ${s.urgent&&lowStock.length>0?"rgba("+C.redRGB+",0.3)":C.border}`,borderRadius:12,padding:"14px 16px"}}><div style={{marginBottom:6}}><Icon name={s.icon} size={20} color={s.urgent&&lowStock.length>0?C.red:C.textMuted}/></div><div style={{color:s.urgent&&lowStock.length>0?C.red:C.text,fontSize:mobile?18:22,fontWeight:700}}>{s.value}</div><div style={{color:C.textMuted,fontSize:11,marginTop:2}}>{s.label}</div></div>)}
  </div>
  <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,overflow:"hidden"}}>
    <div style={{padding:"16px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:`1px solid ${C.border}`,flexWrap:"wrap",gap:8}}>
      <div style={{color:C.text,fontSize:15,fontWeight:700}}>{t("ingredients")}</div>
      <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
        <Btn variant="ghost" size="sm"><Icon name="download" size={13} color={C.textMuted}/>{t("receipt")}</Btn>
        <Btn variant="ghost" size="sm"><Icon name="upload" size={13} color={C.textMuted}/>{t("writeOff")}</Btn>
        <Btn onClick={()=>setShowModal(true)}><Icon name="plus" size={13} color="#fff"/>{t("addIngredient")}</Btn>
      </div>
    </div>
    {mobile?(<div style={{padding:"12px 16px",display:"flex",flexDirection:"column",gap:10}}>{items.map(item=>{const isLow=item.stock<=item.minStock;return(<div key={item.id} style={{background:C.surface,borderRadius:10,padding:"12px 14px",border:`1px solid ${isLow?"rgba("+C.redRGB+",0.3)":C.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}><div style={{color:C.text,fontSize:14,fontWeight:700}}>{item.name}</div><span style={{color:isLow?C.red:C.text,fontSize:13,fontWeight:700}}>{item.stock} {item.unit}</span></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:8}}><span style={{color:C.textMuted,fontSize:11}}>{item.category}</span><span style={{color:C.textDim,fontSize:11}}>•</span><span style={{color:C.textMuted,fontSize:11}}>{item.supplier}</span><span style={{color:C.textDim,fontSize:11}}>•</span><span style={{color:C.textMuted,fontSize:11}}>{fmt(item.cost)}/{item.unit}</span></div><div style={{height:4,background:C.border,borderRadius:2}}><div style={{height:"100%",width:`${Math.min(100,(item.stock/(item.minStock*3))*100)}%`,background:isLow?C.red:C.green,borderRadius:2}}/></div></div>);})}
    </div>):(<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:580}}><thead><tr style={{borderBottom:`1px solid ${C.border}`}}>{[t("name"),t("category"),t("supplier"),t("costPer"),t("stock"),t("minStock"),""].map(h=><th key={h} style={{color:C.textDim,fontSize:10,fontWeight:600,textAlign:"left",padding:"10px 14px",textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</th>)}</tr></thead><tbody>{items.map(item=>{const isLow=item.stock<=item.minStock;return(<tr key={item.id} style={{borderBottom:`1px solid ${C.border}`,background:isLow?`rgba(${C.redRGB},0.03)`:"transparent"}}><td style={{padding:"12px 14px",color:C.text,fontSize:13,fontWeight:600}}>{item.name}</td><td style={{padding:"12px 14px",color:C.textMuted,fontSize:12}}>{item.category}</td><td style={{padding:"12px 14px",color:C.textMuted,fontSize:12}}>{item.supplier}</td><td style={{padding:"12px 14px",color:C.text,fontSize:12}}>{fmt(item.cost)}/{item.unit}</td><td style={{padding:"12px 14px"}}><span style={{color:isLow?C.red:C.text,fontWeight:isLow?700:400,fontSize:13}}>{item.stock} {item.unit}</span></td><td style={{padding:"12px 14px",color:C.textMuted,fontSize:12}}>{item.minStock} {item.unit}</td><td style={{padding:"12px 14px"}}><Btn variant="ghost" size="sm"><Icon name="edit" size={13} color={C.textMuted}/></Btn></td></tr>);})}</tbody></table></div>)}
  </div>
  <Modal open={showModal} onClose={()=>setShowModal(false)} title={t("newIngredient")}><InputField label={t("name")} value={newIng.name} onChange={e=>setNewIng(p=>({...p,name:e.target.value}))} placeholder="Креветки"/><InputField label={t("category")} value={newIng.category} onChange={e=>setNewIng(p=>({...p,category:e.target.value}))} placeholder="Морепродукты"/><InputField label={t("supplier")} value={newIng.supplier} onChange={e=>setNewIng(p=>({...p,supplier:e.target.value}))} placeholder="OceanFresh"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}><InputField label={t("costPer")} value={newIng.cost} onChange={e=>setNewIng(p=>({...p,cost:e.target.value}))} type="number"/><InputField label={t("stock")} value={newIng.stock} onChange={e=>setNewIng(p=>({...p,stock:e.target.value}))} type="number"/><InputField label={t("minStock")} value={newIng.minStock} onChange={e=>setNewIng(p=>({...p,minStock:e.target.value}))} type="number"/></div><SelectField label={t("unit")} value={newIng.unit} onChange={e=>setNewIng(p=>({...p,unit:e.target.value}))} options={["кг","л","г","мл","шт"].map(v=>({value:v,label:v}))}/><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:20}}><Btn variant="secondary" onClick={()=>setShowModal(false)}>{t("cancel")}</Btn><Btn onClick={handleAdd}>{t("addIngredient")}</Btn></div></Modal>
</div>);}
 
function FinancePage(){const {C,t,fmt}=useApp();const mobile=useMobile();const income=finances.filter(i=>i.type==="income").reduce((s,i)=>s+i.amount,0);const expense=finances.filter(i=>i.type==="expense").reduce((s,i)=>s+Math.abs(i.amount),0);const profit=income-expense;
return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12,marginBottom:20}}>
    {[{label:t("income"),val:`+${fmt(income)}`,color:C.green,bg:"rgba(0,224,150,0.06)",border:"rgba(0,224,150,0.15)",icon:"download"},{label:t("expense"),val:`-${fmt(expense)}`,color:C.red,bg:`rgba(${C.redRGB},0.06)`,border:`rgba(${C.redRGB},0.15)`,icon:"upload"},{label:t("profit"),val:(profit>0?"+":"")+fmt(profit),color:profit>0?C.green:C.red,bg:C.card,border:C.border,icon:"trending"}].map(s=><div key={s.label} style={{background:s.bg,border:`1px solid ${s.border}`,borderRadius:14,padding:mobile?"12px":"18px 20px"}}><div style={{marginBottom:6}}><Icon name={s.icon} size={18} color={s.color}/></div><div style={{color:C.textMuted,fontSize:10,marginBottom:4,textTransform:"uppercase",letterSpacing:"0.05em"}}>{s.label}</div><div style={{color:s.color,fontSize:mobile?14:22,fontWeight:700}}>{s.val}</div></div>)}
  </div>
  <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,overflow:"hidden"}}>
    <div style={{padding:"16px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:`1px solid ${C.border}`,flexWrap:"wrap",gap:8}}>
      <div style={{color:C.text,fontSize:15,fontWeight:700}}>{t("cashBook")}</div>
      <div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Btn variant="ghost" size="sm"><Icon name="download" size={13} color={C.textMuted}/>ПКО</Btn><Btn variant="ghost" size="sm"><Icon name="upload" size={13} color={C.textMuted}/>РКО</Btn><Btn variant="ghost" size="sm"><Icon name="receipt" size={13} color={C.textMuted}/>Excel</Btn></div>
    </div>
    {mobile?(<div style={{padding:"12px 16px",display:"flex",flexDirection:"column",gap:10}}>{finances.map(item=><div key={item.id} style={{background:C.surface,borderRadius:10,padding:"12px 14px",border:`1px solid ${C.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:4}}><div style={{color:C.text,fontSize:13,fontWeight:600,flex:1,marginRight:8}}>{item.desc}</div><div style={{color:item.amount>0?C.green:C.red,fontWeight:700,fontSize:14,whiteSpace:"nowrap"}}>{item.amount>0?"+":""}{fmt(item.amount)}</div></div><div style={{display:"flex",gap:8}}><span style={{color:C.textDim,fontSize:11}}>{item.date}</span><span style={{background:C.card,borderRadius:5,padding:"2px 7px",fontSize:10,color:C.textMuted}}>{item.category}</span></div></div>)}</div>):(<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:500}}><thead><tr style={{borderBottom:`1px solid ${C.border}`}}>{[t("date"),t("description"),t("category"),t("account"),t("amount")].map(h=><th key={h} style={{color:C.textDim,fontSize:10,fontWeight:600,textAlign:"left",padding:"10px 18px",textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</th>)}</tr></thead><tbody>{finances.map(item=><tr key={item.id} style={{borderBottom:`1px solid ${C.border}`}}><td style={{padding:"12px 18px",color:C.textMuted,fontSize:12}}>{item.date}</td><td style={{padding:"12px 18px",color:C.text,fontSize:13}}>{item.desc}</td><td style={{padding:"12px 18px"}}><span style={{background:C.surface,borderRadius:6,padding:"3px 8px",fontSize:11,color:C.textMuted}}>{item.category}</span></td><td style={{padding:"12px 18px",color:C.textMuted,fontSize:12}}>{item.account}</td><td style={{padding:"12px 18px",color:item.amount>0?C.green:C.red,fontSize:13,fontWeight:700}}>{item.amount>0?"+":""}{fmt(item.amount)}</td></tr>)}</tbody></table></div>)}
  </div>
</div>);}
 
function StaffPage(){const {C,t,fmt}=useApp();const mobile=useMobile();const [showModal,setShowModal]=useState(false);const [members,setMembers]=useState(staffData);const [newM,setNewM]=useState({name:"",role:"",hourlyRate:""});const handleAdd=()=>{if(!newM.name)return;setMembers(p=>[...p,{id:Date.now(),...newM,hourlyRate:+newM.hourlyRate,hoursThisMonth:0,status:"active"}]);setShowModal(false);setNewM({name:"",role:"",hourlyRate:""});};
return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"flex",justifyContent:"flex-end",marginBottom:16}}><Btn onClick={()=>setShowModal(true)}><Icon name="plus" size={14} color="#fff"/>{t("addStaff")}</Btn></div>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"repeat(2,1fr)",gap:14}}>
    {members.map((m,idx)=>{const salary=m.hourlyRate*m.hoursThisMonth;return(<div key={m.id} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"14px":"18px",display:"flex",gap:14}}>
      <div style={{width:50,height:50,borderRadius:12,flexShrink:0,background:`linear-gradient(135deg,${C.blue}20,${C.purple}20)`,border:`1px solid ${C.blue}30`,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name={staffIcons[idx]||"user"} size={22} color={C.blue}/></div>
      <div style={{flex:1,minWidth:0}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10,flexWrap:"wrap",gap:6}}><div><div style={{color:C.text,fontSize:14,fontWeight:700}}>{m.name}</div><div style={{color:C.textMuted,fontSize:12}}>{m.role}</div></div><Badge status={m.status}/></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8}}>{[{l:t("hourlyRate"),v:fmt(m.hourlyRate)},{l:t("hours"),v:m.hoursThisMonth+"ч"},{l:t("salary"),v:fmt(salary),c:C.green}].map(s=><div key={s.l} style={{background:C.surface,borderRadius:8,padding:"8px 10px"}}><div style={{color:C.textDim,fontSize:9,marginBottom:2}}>{s.l}</div><div style={{color:s.c||C.text,fontSize:12,fontWeight:700}}>{s.v}</div></div>)}</div>
      </div>
    </div>);})}
  </div>
  <Modal open={showModal} onClose={()=>setShowModal(false)} title={t("newEmployee")}><InputField label={t("fullName")} value={newM.name} onChange={e=>setNewM(p=>({...p,name:e.target.value}))} placeholder="Иванов Иван"/><InputField label={t("position")} value={newM.role} onChange={e=>setNewM(p=>({...p,role:e.target.value}))} placeholder="Шеф-повар"/><InputField label={t("hourlyRate")} value={newM.hourlyRate} onChange={e=>setNewM(p=>({...p,hourlyRate:e.target.value}))} type="number" placeholder="850"/><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:20}}><Btn variant="secondary" onClick={()=>setShowModal(false)}>{t("cancel")}</Btn><Btn onClick={handleAdd}>{t("addStaff")}</Btn></div></Modal>
</div>);}
 
function OrdersPage(){const {C,t,fmt}=useApp();const mobile=useMobile();return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:20}}>
    {[{l:"Новые",c:2,color:C.yellow,icon:"plus"},{l:"Готовятся",c:1,color:C.blue,icon:"clock"},{l:"Готовы",c:1,color:C.purple,icon:"check"},{l:"Доставлены",c:2,color:C.green,icon:"truck"}].map(s=><div key={s.l} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,padding:mobile?"10px 12px":"14px 16px",display:"flex",flexDirection:"column",gap:4}}><Icon name={s.icon} size={16} color={s.color}/><div style={{color:C.textMuted,fontSize:mobile?10:12,marginTop:2}}>{s.l}</div><div style={{color:s.color,fontWeight:700,fontSize:mobile?18:22}}>{s.c}</div></div>)}
  </div>
  <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,overflow:"hidden"}}>
    <div style={{padding:"14px 18px",borderBottom:`1px solid ${C.border}`}}><div style={{color:C.text,fontSize:15,fontWeight:700}}>{t("orders")} — сегодня</div></div>
    {mobile?(<div style={{padding:"12px 16px",display:"flex",flexDirection:"column",gap:10}}>{orders.map(o=><div key={o.id} style={{background:C.surface,borderRadius:10,padding:"12px 14px",border:`1px solid ${C.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{color:C.text,fontWeight:700,fontSize:14}}>{o.id}</span><Badge status={o.status}/></div><div style={{display:"flex",flexWrap:"wrap",gap:8,alignItems:"center",marginBottom:6}}><OrderTypeBadge type={o.type}/><span style={{color:C.textDim,fontSize:11}}>{o.time}</span><span style={{color:C.textMuted,fontSize:12}}>{o.items} позиций</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{background:C.card,borderRadius:6,padding:"3px 8px",fontSize:11,color:C.textMuted}}>{o.payment}</span><span style={{color:C.text,fontWeight:700,fontSize:14}}>{fmt(o.total)}</span></div></div>)}</div>):(<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:560}}><thead><tr style={{borderBottom:`1px solid ${C.border}`}}>{[t("order"),t("time"),t("type"),t("qty"),t("amount"),t("payment"),t("status"),t("action")].map(h=><th key={h} style={{color:C.textDim,fontSize:10,fontWeight:600,textAlign:"left",padding:"10px 14px",textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} style={{borderBottom:`1px solid ${C.border}`}}><td style={{padding:"12px 14px",color:C.text,fontSize:13,fontWeight:700}}>{o.id}</td><td style={{padding:"12px 14px",color:C.textMuted,fontSize:12}}>{o.time}</td><td style={{padding:"12px 14px"}}><OrderTypeBadge type={o.type}/></td><td style={{padding:"12px 14px",color:C.textMuted,fontSize:12}}>{o.items}</td><td style={{padding:"12px 14px",color:C.text,fontSize:13,fontWeight:700}}>{fmt(o.total)}</td><td style={{padding:"12px 14px"}}><span style={{background:C.surface,borderRadius:6,padding:"3px 8px",fontSize:11,color:C.textMuted}}>{o.payment}</span></td><td style={{padding:"12px 14px"}}><Badge status={o.status}/></td><td style={{padding:"12px 14px"}}><Btn variant="ghost" size="sm">{t("details")}</Btn></td></tr>)}</tbody></table></div>)}
  </div>
</div>);}
 
function RestaurantsPage(){const {C,t,fmt}=useApp();const mobile=useMobile();const [showModal,setShowModal]=useState(false);return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"flex",justifyContent:"flex-end",marginBottom:16}}><Btn onClick={()=>setShowModal(true)}><Icon name="plus" size={14} color="#fff"/>{t("newRestaurant")}</Btn></div>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"repeat(3,1fr)",gap:14}}>
    {restaurants.map(r=><div key={r.id} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:18,overflow:"hidden",transition:"all 0.2s"}} onMouseEnter={e=>{if(!mobile){e.currentTarget.style.borderColor=C.borderLight;e.currentTarget.style.transform="translateY(-2px)";}}} onMouseLeave={e=>{e.currentTarget.style.borderColor=C.border;e.currentTarget.style.transform="translateY(0)";}}>
      <div style={{background:`linear-gradient(135deg,${C.redGlow},transparent)`,padding:"22px 20px 16px",borderBottom:`1px solid ${C.border}`,display:"flex",alignItems:"center",gap:14}}>
        <div style={{width:48,height:48,borderRadius:14,background:`rgba(${C.redRGB},0.1)`,border:`1px solid rgba(${C.redRGB},0.2)`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Icon name="restaurants" size={24} color={C.red}/></div>
        <div style={{flex:1}}><div style={{color:C.text,fontSize:16,fontWeight:700}}>{r.name}</div><div style={{color:C.textMuted,fontSize:12}}>{r.cuisine}</div></div>
        <Badge status={r.status}/>
      </div>
      <div style={{padding:"16px 20px"}}>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:14}}>{[{l:"Выручка",v:fmt(r.revenue),icon:"dollar"},{l:t("orders"),v:r.orders.toLocaleString(),icon:"receipt"}].map(s=><div key={s.l} style={{background:C.surface,borderRadius:9,padding:"10px 12px"}}><div style={{display:"flex",alignItems:"center",gap:5,marginBottom:2}}><Icon name={s.icon} size={11} color={C.textDim}/><div style={{color:C.textDim,fontSize:10}}>{s.l}</div></div><div style={{color:C.text,fontSize:14,fontWeight:700}}>{s.v}</div></div>)}</div>
        <div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Btn variant="ghost" size="sm"><Icon name="settings" size={13} color={C.textMuted}/></Btn><Btn variant="ghost" size="sm"><Icon name="globe" size={13} color={C.textMuted}/></Btn><Btn size="sm" fullWidth={mobile}>{t("manage")}</Btn></div>
      </div>
    </div>)}
    <div onClick={()=>setShowModal(true)} style={{background:C.card,border:`2px dashed ${C.border}`,borderRadius:18,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:36,cursor:"pointer",transition:"all 0.2s",minHeight:200}} onMouseEnter={e=>{e.currentTarget.style.borderColor=C.red;e.currentTarget.style.background=C.redGlow;}} onMouseLeave={e=>{e.currentTarget.style.borderColor=C.border;e.currentTarget.style.background=C.card;}}>
      <div style={{width:44,height:44,borderRadius:11,background:C.surface,border:`1px solid ${C.border}`,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:10}}><Icon name="plus" size={22} color={C.textMuted}/></div>
      <div style={{color:C.text,fontSize:14,fontWeight:600}}>{t("newRestaurant")}</div>
      <div style={{color:C.textDim,fontSize:11,marginTop:4}}>{"< 1 ч"}</div>
    </div>
  </div>
  <Modal open={showModal} onClose={()=>setShowModal(false)} title={t("newRestaurant")}><InputField label={t("restaurantName")} value="" onChange={()=>{}} placeholder="La Bella Italia"/><InputField label={t("cuisine")} value="" onChange={()=>{}} placeholder="Italian"/><InputField label={t("subdomain")} value="" onChange={()=>{}} placeholder="labella.festo.io"/><InputField label={t("ownDomain")} value="" onChange={()=>{}} placeholder="labella.com"/><SelectField label={t("template")} value="modern" onChange={()=>{}} options={[{value:"modern",label:"Modern Dark"},{value:"classic",label:"Classic Light"},{value:"bold",label:"Bold & Bright"}]}/><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:20}}><Btn variant="secondary" onClick={()=>setShowModal(false)}>{t("cancel")}</Btn><Btn>{t("createRestaurant")}</Btn></div></Modal>
</div>);}
 
function AnalyticsPage(){const {C,t,fmt}=useApp();const mobile=useMobile();return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"repeat(3,1fr)",gap:12,marginBottom:20}}>
    {[{label:t("monthRevenue"),value:fmt(2184000),change:"+18%",icon:"dollar"},{label:t("monthOrders"),value:"2 991",change:"+12%",icon:"receipt"},{label:t("avgCheck"),value:fmt(1104),change:"+5%",icon:"trending"}].map(s=><div key={s.label} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"14px":"20px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><Icon name={s.icon} size={22} color={C.textMuted}/><span style={{color:C.green,fontSize:11,fontWeight:600,background:"rgba(0,224,150,0.1)",padding:"3px 8px",borderRadius:6}}>{s.change}</span></div><div style={{color:C.text,fontSize:mobile?20:24,fontWeight:700,marginBottom:2}}>{s.value}</div><div style={{color:C.textMuted,fontSize:11}}>{s.label}</div></div>)}
  </div>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"3fr 2fr",gap:14}}>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"20px"}}><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:4}}>{t("weekRevenue")}</div><div style={{color:C.textMuted,fontSize:12,marginBottom:16}}>Июнь 2026</div><BarChart data={revenueData}/><div style={{display:"flex",justifyContent:"space-between",marginTop:6}}>{revenueData.map(d=><div key={d.day} style={{flex:1,textAlign:"center"}}><div style={{color:C.textDim,fontSize:9}}>{fmt(d.value/1000,"k")}</div></div>)}</div></div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"20px"}}><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:16}}>{t("topDishesTitle")}</div>{menuItems.slice(0,5).map((item,i)=><div key={item.id} style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><span style={{color:i<3?C.red:C.textDim,fontSize:11,fontWeight:700,width:18}}>#{i+1}</span><div style={{width:28,height:28,borderRadius:7,background:C.surface,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name="menu" size={14} color={C.textMuted}/></div><div style={{flex:1}}><div style={{color:C.text,fontSize:12,fontWeight:600}}>{item.name}</div><div style={{height:3,background:C.surface,borderRadius:2,marginTop:3}}><div style={{height:"100%",width:`${80-i*14}%`,background:i===0?C.red:C.border,borderRadius:2}}/></div></div><span style={{color:C.textMuted,fontSize:11,flexShrink:0}}>{fmt(item.price)}</span></div>)}</div>
  </div>
</div>);}
 
function SettingsPage(){const {C,t,lang,setLang,currency,setCurrency,dark,setDark,accent,setAccent,viewMode,setViewMode}=useApp();const mobile=useMobile();const [name,setName]=useState("Sakura Garden");
const integrations=[{name:"POS-терминал",status:"connected",icon:"pos"},{name:"Кухонный принтер",status:"connected",icon:"printer"},{name:"Онлайн-эквайринг",status:"pending",icon:"card"},{name:"QR Pay",status:"disconnected",icon:"qr"},{name:"SMS",status:"connected",icon:"sms"},{name:"Push",status:"connected",icon:"push"}];
const roles=[{role:"Super Admin",perms:"Полный доступ",icon:"crown"},{role:"Owner",perms:"Свои рестораны",icon:"building"},{role:"Restaurant Admin",perms:"Меню, персонал, склад",icon:"settings"},{role:"Manager",perms:"Заказы, смены, табель",icon:"orders"},{role:"Cashier",perms:"Касса и заказы",icon:"finance"}];
return(<div style={{padding:mobile?"16px":"24px",overflow:"auto",flex:1}}>
  <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"1fr 1fr",gap:14}}>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"22px"}}><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:18}}>{t("generalSettings")}</div><InputField label={t("restaurantName")} value={name} onChange={e=>setName(e.target.value)}/><SelectField label={t("language")} value={lang} onChange={e=>setLang(e.target.value)} options={[{value:"ru",label:"🇷🇺 Русский"},{value:"en",label:"🇬🇧 English"},{value:"zh",label:"🇨🇳 中文"},{value:"ja",label:"🇯🇵 日本語"},{value:"es",label:"🇪🇸 Español"},{value:"fr",label:"🇫🇷 Français"}]}/><SelectField label={t("currency")} value={currency} onChange={e=>setCurrency(e.target.value)} options={Object.entries(CURRENCIES).map(([k,v])=>({value:k,label:`${v.symbol} ${k} — ${v.name}`}))}/><div style={{marginBottom:16}}><label style={{display:"block",color:C.textMuted,fontSize:11,marginBottom:8,textTransform:"uppercase",letterSpacing:"0.05em"}}>Тема</label><div style={{display:"flex",gap:8}}><button onClick={()=>setDark(false)} style={{flex:1,padding:"10px",borderRadius:10,border:`2px solid ${!dark?C.red:C.border}`,background:!dark?C.redGlow:C.surface,color:!dark?C.red:C.textMuted,cursor:"pointer",fontFamily:"inherit",fontSize:12,fontWeight:600,display:"flex",alignItems:"center",justifyContent:"center",gap:6}}><Icon name="sun" size={14} color={!dark?C.red:C.textMuted}/>{t("lightMode")}</button><button onClick={()=>setDark(true)} style={{flex:1,padding:"10px",borderRadius:10,border:`2px solid ${dark?C.red:C.border}`,background:dark?C.redGlow:C.surface,color:dark?C.red:C.textMuted,cursor:"pointer",fontFamily:"inherit",fontSize:12,fontWeight:600,display:"flex",alignItems:"center",justifyContent:"center",gap:6}}><Icon name="moon" size={14} color={dark?C.red:C.textMuted}/>{t("darkMode")}</button></div></div><Btn fullWidth><Icon name="check" size={14} color="#fff"/>{t("saveChanges")}</Btn></div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"22px"}}>
      <div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:6}}>Режим отображения</div>
      <div style={{color:C.textMuted,fontSize:12,marginBottom:18}}>Принудительно задать макет для текущего устройства</div>
      <div style={{display:"flex",flexDirection:"column",gap:10}}>
        {[{v:"auto",label:"Авто",desc:"По размеру экрана",icon:"activity"},{v:"desktop",label:"ПК версия",desc:"Всегда десктопный вид",icon:"pos"},{v:"mobile",label:"Мобильная версия",desc:"Всегда мобильный вид",icon:"push"}].map(opt=>(
          <button key={opt.v} onClick={()=>setViewMode(opt.v)}
            style={{background:viewMode===opt.v?C.redGlow:C.surface,border:`2px solid ${viewMode===opt.v?"rgba("+C.redRGB+",0.4)":C.border}`,borderRadius:12,padding:"12px 16px",display:"flex",alignItems:"center",gap:12,cursor:"pointer",fontFamily:"inherit",textAlign:"left",transition:"all 0.15s"}}>
            <div style={{width:38,height:38,borderRadius:10,background:viewMode===opt.v?`rgba(${C.redRGB},0.15)`:C.card,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>
              <Icon name={opt.icon} size={18} color={viewMode===opt.v?C.red:C.textMuted}/>
            </div>
            <div style={{flex:1}}>
              <div style={{color:viewMode===opt.v?C.red:C.text,fontSize:13,fontWeight:600}}>{opt.label}</div>
              <div style={{color:C.textDim,fontSize:11,marginTop:1}}>{opt.desc}</div>
            </div>
            {viewMode===opt.v&&<div style={{width:20,height:20,borderRadius:"50%",background:C.red,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name="check" size={12} color="#fff"/></div>}
          </button>
        ))}
      </div>
    </div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"22px"}}><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:18}}>{t("brandStyle")}</div><div style={{marginBottom:16}}><label style={{display:"block",color:C.textMuted,fontSize:11,marginBottom:8,textTransform:"uppercase",letterSpacing:"0.05em"}}>{t("accentColor")}</label><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{["#7B00FF","#FF2D20","#4B7BFF","#00E096","#FFD60A","#FF6B35"].map(c=><div key={c} onClick={()=>setAccent(c)} style={{width:36,height:36,borderRadius:9,background:c,cursor:"pointer",border:accent===c?"3px solid white":"2px solid transparent",boxShadow:accent===c?`0 0 14px ${c}`:"none",transition:"all 0.15s"}}/>)}</div></div><div style={{background:C.surface,borderRadius:10,padding:"14px 16px",marginBottom:16}}><div style={{color:C.textMuted,fontSize:11,marginBottom:8,textTransform:"uppercase",letterSpacing:"0.05em"}}>{t("preview")}</div><div style={{display:"flex",alignItems:"center",gap:10}}><FestoLogo size={34}/><div><div style={{color:C.text,fontSize:14,fontWeight:700}}>{name}</div><div style={{color:accent,fontSize:11,display:"flex",alignItems:"center",gap:4}}><Icon name="activity" size={10} color={accent}/>● {t("online")}</div></div></div></div><InputField label={t("domain")} value="sakura.festo.io" onChange={()=>{}}/><Btn fullWidth><Icon name="palette" size={14} color="#fff"/>{t("applyStyle")}</Btn></div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"22px"}}><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:16}}>{t("integrations")}</div>{integrations.map(i=><div key={i.name} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:`1px solid ${C.border}`}}><div style={{width:32,height:32,borderRadius:8,background:C.surface,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name={i.icon} size={16} color={C.textMuted}/></div><span style={{flex:1,color:C.text,fontSize:13}}>{i.name}</span><Badge status={i.status==="connected"?"active":i.status==="pending"?"preparing":"on-leave"}/><Btn variant="ghost" size="sm">{i.status==="connected"?t("change"):t("connect")}</Btn></div>)}</div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:mobile?"16px":"22px"}}><div style={{color:C.text,fontSize:15,fontWeight:700,marginBottom:16}}>{t("roles")}</div>{roles.map(r=><div key={r.role} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:`1px solid ${C.border}`}}><div style={{width:32,height:32,borderRadius:8,background:`rgba(${C.redRGB},0.08)`,display:"flex",alignItems:"center",justifyContent:"center"}}><Icon name={r.icon} size={16} color={C.red}/></div><div style={{flex:1}}><div style={{color:C.text,fontSize:13,fontWeight:600}}>{r.role}</div><div style={{color:C.textDim,fontSize:11}}>{r.perms}</div></div><Btn variant="ghost" size="sm"><Icon name="settings" size={12} color={C.textMuted}/>{t("configure")}</Btn></div>)}</div>
  </div>
</div>);}
 
export default function App(){
  const [active,setActive]=useState("dashboard");const [sidebarOpen,setSidebarOpen]=useState(false);const [dark,setDark]=useState(true);const [lang,setLang]=useState("ru");const [currency,setCurrency]=useState("RUB");const [accent,setAccent]=useState("#7B00FF");const [viewMode,setViewMode]=useState("auto");const [notifOpen,setNotifOpen]=useState(false);const [notifs,setNotifs]=useState(NOTIFICATIONS);const mobile=useMobile();
  const C=makePalette(dark,accent);
  const t=(key)=>{const d=T[lang]||T.ru;return d[key]||T.ru[key]||key;};
  const fmt=(n,suffix="")=>{const cur=CURRENCIES[currency]||CURRENCIES.RUB;const val=Math.round(+n*RATES[currency]);const f=new Intl.NumberFormat(cur.locale,{maximumFractionDigits:0}).format(val);return`${cur.symbol}${f}${suffix}`;};
  const unread=notifs.filter(n=>!n.read).length;
  const markAll=()=>setNotifs(ns=>ns.map(n=>({...n,read:true})));
  const ctx={C,t,fmt,dark,setDark,lang,setLang,currency,setCurrency,accent,setAccent,viewMode,setViewMode};
  const pages={dashboard:<DashboardPage/>,restaurants:<RestaurantsPage/>,menu:<MenuPage/>,orders:<OrdersPage/>,inventory:<InventoryPage/>,finance:<FinancePage/>,staff:<StaffPage/>,analytics:<AnalyticsPage/>,settings:<SettingsPage/>};
  return(<AppContext.Provider value={ctx}>
    <div style={{display:"flex",height:"100vh",background:C.bg,fontFamily:"'Inter',-apple-system,BlinkMacSystemFont,sans-serif",color:C.text,overflow:"hidden",transition:"background 0.3s,color 0.3s"}}>
      {viewMode!=="auto"&&<div style={{position:"fixed",top:0,left:0,right:0,height:3,background:`linear-gradient(90deg,${C.red},${C.purple})`,zIndex:9999,boxShadow:`0 0 10px rgba(${C.redRGB},0.5)`}}/>}
      <style>{`*{box-sizing:border-box;}::-webkit-scrollbar{width:4px;height:4px;}::-webkit-scrollbar-track{background:transparent;}::-webkit-scrollbar-thumb{background:${dark?"#2A2A40":"#C8C8DC"};border-radius:2px;}input::placeholder{color:${C.textDim};}input,select{caret-color:${C.red};}select option{background:${C.card};color:${C.text};}`}</style>
      <Sidebar active={active} onNav={setActive} open={sidebarOpen} onClose={()=>setSidebarOpen(false)}/>
      <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden",minWidth:0}}><TopBar section={active} onBurger={()=>setSidebarOpen(o=>!o)} notifCount={unread} onBell={()=>setNotifOpen(o=>!o)}/>{pages[active]}</div>
      <NotifPanel open={notifOpen} onClose={()=>setNotifOpen(false)} notifs={notifs} onMarkAll={markAll}/>
    </div>
  </AppContext.Provider>);
}